import { ReportRepository } from '@adapters/dashboard/persistence/reports.repository';
import { Injectable, Logger } from '@nestjs/common';
import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';

export type ReportFormat = 'pdf' | 'excel';

/**
 * Locale set we actively render labels for. Keep this list aligned with
 * `apps/webClient/src/infrastructure/i18n/i18n.ts` `SUPPORTED_LOCALES`.
 * The controller silently falls back to `en-US` if a request asks for
 * something outside the set, so the report always renders.
 */
export type ExportLocale = 'en-US' | 'es-CO';

/**
 * Postgres `to_char(date, 'Mon')` returns English 3-letter abbreviations.
 * Translate them at the presentation layer (this service) so the SQL
 * contract stays stable for every other consumer of `getMonthlyOverview`.
 *
 * Any locale whose language family starts with `es` reuses the same
 * abbreviations as `es-CO`; everything else stays in English.
 */
const EN_TO_ES_MONTHS: Record<string, string> = {
  Jan: 'Ene',
  Feb: 'Feb',
  Mar: 'Mar',
  Apr: 'Abr',
  May: 'May',
  Jun: 'Jun',
  Jul: 'Jul',
  Aug: 'Ago',
  Sep: 'Sep',
  Oct: 'Oct',
  Nov: 'Nov',
  Dec: 'Dic',
};

function localizeMonthName(
  enAbbr: string | undefined,
  locale: ExportLocale,
): string {
  if (!enAbbr) return '';
  if (locale === 'es-CO') {
    return EN_TO_ES_MONTHS[enAbbr] ?? enAbbr;
  }
  return enAbbr;
}

/**
 * Section / table / KPI labels. Keyed by ExportLocale so missing
 * translations fail the build (`as const satisfies …` below guarantees
 * every key is present in every locale).
 *
 * Add new labels here, not inline. The helper below is the only path
 * through which the PDF / Excel pipelines reach a string the user sees.
 */
type StringKey =
  | 'financialReport'
  | 'generated'
  | 'totalIncome'
  | 'totalExpenses'
  | 'netSavings'
  | 'monthlyBreakdown'
  | 'spendingByCategory'
  | 'month'
  | 'income'
  | 'expenses'
  | 'savings'
  | 'category'
  | 'total'
  | 'metric'
  | 'value'
  | 'summary'
  | 'reportYear'
  | 'footer';

const STRINGS = {
  'en-US': {
    financialReport: 'Financial Report',
    generated: 'Generated',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    netSavings: 'Net Savings',
    monthlyBreakdown: 'Monthly Breakdown',
    spendingByCategory: 'Spending by Category',
    month: 'Month',
    income: 'Income',
    expenses: 'Expenses',
    savings: 'Savings',
    category: 'Category',
    total: 'Total',
    metric: 'Metric',
    value: 'Value',
    summary: 'Summary',
    reportYear: 'Report Year',
    footer:
      'This report was generated by BudgetGenius. Income and expense values are sourced from your transactions.',
  },
  'es-CO': {
    financialReport: 'Informe Financiero',
    generated: 'Generado',
    totalIncome: 'Ingresos Totales',
    totalExpenses: 'Gastos Totales',
    netSavings: 'Ahorro Neto',
    monthlyBreakdown: 'Desglose Mensual',
    spendingByCategory: 'Gastos por Categoría',
    month: 'Mes',
    income: 'Ingresos',
    expenses: 'Gastos',
    savings: 'Ahorros',
    category: 'Categoría',
    total: 'Total',
    metric: 'Métrica',
    value: 'Valor',
    summary: 'Resumen',
    reportYear: 'Año del Informe',
    footer:
      'Este informe fue generado por BudgetGenius. Los valores de ingresos y gastos provienen de tus transacciones.',
  },
} as const satisfies Record<ExportLocale, Record<StringKey, string>>;

function localize(key: StringKey, locale: ExportLocale): string {
  return STRINGS[locale][key];
}

export interface ExportPayload {
  filename: string;
  contentType: string;
  buffer: Buffer;
}

/**
 * Service that produces downloadable PDF / Excel reports for a given user
 * and year. The data layer is delegated to the existing ReportRepository
 * so we don't duplicate query logic — only the presentation layer
 * (PDFKit document generation / ExcelJS workbook build) lives here.
 *
 * Both pipelines return a Buffer; the controller streams it back with
 * the appropriate Content-Type and Content-Disposition headers.
 */
@Injectable()
export class ReportExportService {
  private readonly logger = new Logger(ReportExportService.name);

  constructor(private readonly repo: ReportRepository) {}

  async export(
    userId: number,
    year: number,
    format: ReportFormat,
    locale: ExportLocale = 'en-US',
  ): Promise<ExportPayload> {
    if (format === 'pdf') {
      return this.exportPdf(userId, year, locale);
    }
    return this.exportExcel(userId, year, locale);
  }

  // ─── PDF ──────────────────────────────────────────────────────────────

  private async exportPdf(
    userId: number,
    year: number,
    locale: ExportLocale,
  ): Promise<ExportPayload> {
    const [monthly, categories] = await Promise.all([
      this.repo.getMonthlyOverview(year, userId),
      // Re-use the existing category breakdown spanning all months of the
      // selected year. This keeps the PDF aligned with what the user sees
      // on the Categories tab.
      this.repo.getCategoryBreakdown(
        new Date(Date.UTC(year, 0, 1)),
        new Date(Date.UTC(year, 11, 31)),
        userId,
      ),
    ]);

    // Replace the Postgres English 3-letter rows with locale-aware labels
    // once, up-front. Both the PDF and Excel pipelines consume this array
    // independently, so translating here avoids duplication downstream.
    const localizedMonthly = (monthly ?? []).map((row) => ({
      ...row,
      month: localizeMonthName(row.month, locale),
    }));

    const totals = this.computeTotals(localizedMonthly);
    const safeCategories = (categories ?? []).sort(
      (a, b) => Math.abs(Number(b.total) || 0) - Math.abs(Number(a.total) || 0),
    );

    // PDFKit writes to a Node stream; we collect chunks into a Buffer so the
    // controller can return it through Nest's response pipeline.
    //
    // IMPORTANT: `doc.end()` MUST be called even if `renderPdf` throws
    // synchronously. If a document method (text/roundedRect/addPage) raises,
    // the promise would otherwise neither resolve nor reject — control
    // returns before `doc.end()` runs, no `end`/`error` event fires, and the
    // Nest request hangs. The try/finally guarantees flush.
    const buffer = await new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 48,
        info: {
          // Localized so the file metadata matches what the reader sees.
          Title: `${localize('financialReport', locale)} - ${year}`,
          Author: 'BudgetGenius',
        },
      });
      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err) => reject(err));

      try {
        this.renderPdf(
          doc,
          year,
          localizedMonthly,
          safeCategories,
          totals,
          locale,
        );
      } finally {
        doc.end();
      }
    });

    return {
      filename: `budget-report-${year}.pdf`,
      contentType: 'application/pdf',
      buffer,
    };
  }

  private renderPdf(
    doc: PDFKit.PDFDocument,
    year: number,
    monthly: { month: string; income: number; expenses: number }[],
    categories: { category: string; total: number }[],
    totals: { income: number; expenses: number; net: number },
    locale: ExportLocale,
  ): void {
    const titleColor = '#1f2937';
    const accent = '#7c3aed';
    const danger = '#dc2626';
    const success = '#059669';

    // Header
    doc
      .fontSize(22)
      .fillColor(titleColor)
      .font('Helvetica-Bold')
      .text('BudgetGenius', { align: 'left' });
    doc
      .fontSize(18)
      .fillColor(accent)
      .text(`${localize('financialReport', locale)} — ${year}`, {
        align: 'left',
      });
    doc
      .fontSize(10)
      .fillColor('#6b7280')
      .font('Helvetica')
      .text(
        // Locale-aware "Generated" + locale-aware timestamp.
        `${localize('generated', locale)} ${new Date().toLocaleDateString(
          locale,
          {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
          },
        )}`,
        { align: 'left' },
      );
    doc.moveDown(1.5);

    // KPI tiles
    const kpiY = doc.y;
    this.drawKpiTile(
      doc,
      48,
      kpiY,
      localize('totalIncome', locale),
      totals.income,
      success,
    );
    this.drawKpiTile(
      doc,
      230,
      kpiY,
      localize('totalExpenses', locale),
      totals.expenses,
      danger,
    );
    this.drawKpiTile(
      doc,
      412,
      kpiY,
      localize('netSavings', locale),
      totals.net,
      accent,
    );
    doc.y = kpiY + 80;
    doc.moveDown(1);

    // Monthly breakdown
    doc
      .fontSize(14)
      .fillColor(titleColor)
      .font('Helvetica-Bold')
      .text(localize('monthlyBreakdown', locale));
    doc.moveDown(0.5);
    this.drawTable(
      doc,
      [
        localize('month', locale),
        localize('income', locale),
        localize('expenses', locale),
        localize('savings', locale),
      ],
      monthly.map((row) => [
        row.month,
        this.formatMoney(row.income),
        this.formatMoney(row.expenses),
        this.formatMoney(
          (Number(row.income) || 0) - (Number(row.expenses) || 0),
        ),
      ]),
      { startX: 48, columnWidths: [80, 140, 140, 140] },
    );

    // Categories
    if (categories.length > 0) {
      doc.addPage();
      doc
        .fontSize(14)
        .fillColor(titleColor)
        .font('Helvetica-Bold')
        .text(localize('spendingByCategory', locale));
      doc.moveDown(0.5);
      this.drawTable(
        doc,
        [localize('category', locale), localize('total', locale)],
        categories.map((row) => [
          row.category,
          this.formatMoney(Math.abs(Number(row.total) || 0)),
        ]),
        { startX: 48, columnWidths: [200, 200] },
      );
    }

    // Footer
    doc.moveDown(2);
    doc
      .fontSize(9)
      .fillColor('#9ca3af')
      .font('Helvetica-Oblique')
      .text(localize('footer', locale), { align: 'center', width: 500 });
  }

  private drawKpiTile(
    doc: PDFKit.PDFDocument,
    x: number,
    y: number,
    label: string,
    value: number,
    color: string,
  ): void {
    const width = 160;
    const height = 64;
    doc
      .roundedRect(x, y, width, height, 8)
      .lineWidth(1)
      .strokeColor('#e5e7eb')
      .stroke();
    doc
      .fontSize(10)
      .fillColor('#6b7280')
      .font('Helvetica')
      .text(label.toUpperCase(), x + 12, y + 12, { width: width - 24 });
    doc
      .fontSize(18)
      .fillColor(color)
      .font('Helvetica-Bold')
      .text(this.formatMoney(value), x + 12, y + 30, { width: width - 24 });
  }

  // Phased: simple line-shrink table that fits an A4 width without overflow.
  private drawTable(
    doc: PDFKit.PDFDocument,
    headers: string[],
    rows: string[][],
    opts: { startX: number; columnWidths: number[] },
  ): void {
    const rowHeight = 22;
    const startY = doc.y + 4;
    let y = startY;

    const drawRow = (cells: string[], isHeader: boolean): void => {
      let cellX = opts.startX;
      cells.forEach((cell, idx) => {
        const width = opts.columnWidths[idx] ?? 80;
        if (isHeader) {
          doc
            .rect(cellX, y, width, rowHeight)
            .fillAndStroke('#f3f4f6', '#e5e7eb');
          doc
            .fillColor('#374151')
            .font('Helvetica-Bold')
            .fontSize(10)
            .text(cell, cellX + 8, y + 6, { width: width - 16, align: 'left' });
        } else {
          doc
            .rect(cellX, y, width, rowHeight)
            .strokeColor('#e5e7eb')
            .lineWidth(0.5)
            .stroke();
          doc
            .fillColor('#111827')
            .font('Helvetica')
            .fontSize(10)
            .text(cell, cellX + 8, y + 6, { width: width - 16, align: 'left' });
        }
        cellX += width;
      });
      y += rowHeight;
    };

    drawRow(headers, true);
    rows.forEach((row, idx) => {
      // Insert a page break if we run out of vertical space.
      // PDFPage exposes its margins as `margins: { top, left, right, bottom }`.
      if (y > doc.page.height - doc.page.margins.bottom - rowHeight) {
        doc.addPage();
        y = doc.page.margins.top;
      }
      drawRow(row, false);
    });

    doc.y = y + 4;
  }

  // ─── Excel ────────────────────────────────────────────────────────────

  private async exportExcel(
    userId: number,
    year: number,
    locale: ExportLocale,
  ): Promise<ExportPayload> {
    const [monthly, categories] = await Promise.all([
      this.repo.getMonthlyOverview(year, userId),
      this.repo.getCategoryBreakdown(
        new Date(Date.UTC(year, 0, 1)),
        new Date(Date.UTC(year, 11, 31)),
        userId,
      ),
    ]);

    // Translate Postgres English month strings once and feed the rest of
    // the workbook build off this array (savings are derived in-place).
    const localizedMonthly = (monthly ?? []).map((row) => ({
      ...row,
      month: localizeMonthName(row.month, locale),
    }));

    const totals = this.computeTotals(localizedMonthly);
    const safeMonthly = localizedMonthly;
    const safeCategories = (categories ?? []).sort(
      (a, b) => Math.abs(Number(b.total) || 0) - Math.abs(Number(a.total) || 0),
    );

    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'BudgetGenius';
    workbook.created = new Date();

    // Sheet: Summary
    const summary = workbook.addWorksheet(localize('summary', locale));
    summary.columns = [
      { header: localize('metric', locale), key: 'metric', width: 24 },
      { header: localize('value', locale), key: 'value', width: 22 },
    ];
    summary.addRow({ metric: localize('reportYear', locale), value: year });
    summary.addRow({
      metric: localize('generated', locale),
      value: new Date().toISOString(),
    });
    summary.addRow({
      metric: localize('totalIncome', locale),
      value: Number(totals.income.toFixed(2)),
    });
    summary.addRow({
      metric: localize('totalExpenses', locale),
      value: Number(totals.expenses.toFixed(2)),
    });
    summary.addRow({
      metric: localize('netSavings', locale),
      value: Number(totals.net.toFixed(2)),
    });
    this.styleHeaderRow(summary.getRow(1));

    // Sheet: Monthly Breakdown
    const monthlySheet = workbook.addWorksheet(
      localize('monthlyBreakdown', locale),
    );
    monthlySheet.columns = [
      { header: localize('month', locale), key: 'month', width: 16 },
      { header: localize('income', locale), key: 'income', width: 18 },
      { header: localize('expenses', locale), key: 'expenses', width: 18 },
      { header: localize('savings', locale), key: 'savings', width: 18 },
    ];
    safeMonthly.forEach((row) => {
      const income = Number(row.income) || 0;
      const expenses = Number(row.expenses) || 0;
      monthlySheet.addRow({
        month: row.month,
        income: Number(income.toFixed(2)),
        expenses: Number(expenses.toFixed(2)),
        savings: Number((income - expenses).toFixed(2)),
      });
    });
    this.styleHeaderRow(monthlySheet.getRow(1));

    // Sheet: Categories
    const categoriesSheet = workbook.addWorksheet(
      localize('spendingByCategory', locale),
    );
    categoriesSheet.columns = [
      { header: localize('category', locale), key: 'category', width: 28 },
      { header: localize('total', locale), key: 'total', width: 18 },
    ];
    safeCategories.forEach((row) => {
      categoriesSheet.addRow({
        category: row.category,
        total: Number(Math.abs(Number(row.total) || 0).toFixed(2)),
      });
    });
    this.styleHeaderRow(categoriesSheet.getRow(1));

    const bufferArray = await workbook.xlsx.writeBuffer();
    // ExcelJS returns ArrayBufferView in Node; convert to Node Buffer.
    const buffer = Buffer.from(bufferArray);

    return {
      filename: `budget-report-${year}.xlsx`,
      contentType:
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      buffer,
    };
  }

  private styleHeaderRow(row: ExcelJS.Row): void {
    row.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    row.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF7C3AED' },
    };
    row.alignment = { vertical: 'middle', horizontal: 'left' };
  }

  // ─── Helpers ──────────────────────────────────────────────────────────

  private computeTotals(
    monthly: { month: string; income: number; expenses: number }[] | undefined,
  ): { income: number; expenses: number; net: number } {
    const safe = monthly ?? [];
    const income = safe.reduce(
      (acc, row) => acc + (Number(row.income) || 0),
      0,
    );
    const expenses = safe.reduce(
      (acc, row) => acc + (Number(row.expenses) || 0),
      0,
    );
    return {
      income,
      expenses,
      net: income - expenses,
    };
  }

  private formatMoney(value: number): string {
    const safe = Number(value) || 0;
    return safe.toLocaleString('en-US', {
      style: 'currency',
      currency: 'USD',
    });
  }
}
