name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [ main ]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        # Inyectamos la URL de la API durante el build
        run: pnpm --filter @apps/webClient build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BUDGETGENIUSIA }}
          channelId: live
          projectId: budgetgeniusia
